### ISSUE TITLE
fatal error: pybind11/pybind11.h: No such file or directory

### ISSUE THREAD

**Issue by chadgh** [tbenthompson/cppimport#2]
I tried following the example in the README and got the following error:

```
/tmp/tmp826vncgj/somecode.cpp:2:36: fatal error: pybind11/pybind11.h: No such file or directory
     #include <pybind11/pybind11.h>
```

**Comment by tbenthompson** [comment]
This is a problem with the installation. The pybind11 dependency isn't being found. It's hard to easily say what the problem is.

Some quick questions:
1. Did you use pip to install? 
2. Operating system? 
3. Python version?

Would you be willing to run these lines and then list the files in the folders that are output for me? 
```python
>>> import pybind11
>>> pybind11.get_include()
'/usr/local/include/python2.7'
>>> pybind11.get_include(True)
'/home/tbent/.local/include/python2.7'
```

**Comment by chadgh** [comment]
1. Yes I used pip to install
2. Arch Linux
3. Python 3.5.1
4. Virtualenv

```python
>>> import pybind11
>>> pybind11.get_include()
'/home/chadgh/.pyenv/versions/3.5.1/include/python3.5m'
>>> pybind11.get_include(True)
'/home/chadgh/.local/include/python3.5m'
```

So maybe 3.5.1 is not supported?

**Comment by tbenthompson** [comment]
I use 3.5 for development, so that's not it. 

Could you list the files in these folders?
/home/chadgh/.pyenv/versions/3.5.1/include/python3.5m/pybind11
/home/chadgh/.local/include/python3.5m/pybind11

**Comment by chadgh** [comment]
Those paths don't exist. I have `/home/chadgh/.pyenv/versions/3.5.1/include/python3.5m/` but no `pybind11` in there. And I have up to `/home/chadgh/.local/` but no `include`.

I also did a search (using the `find` command) at those levels and didn't find anything called `pybind11`.

**Comment by chadgh** [comment]
In the virtualenvironment there is `./lib/python3.5/site-packages/pybind11` and `./include/site/python3.5/pybind11`

**Comment by tbenthompson** [comment]
Want to list the files in `./include/site/python3.5/pybind11`? I think pybind11 is getting confused about where it installed itself!

**Comment by chadgh** [comment]
Sure

```
attr.h
cast.h
common.h
complex.h
descr.h
functional.h
numpy.h
operators.h
pybind11.h
pytypes.h
stl.h
typeid.h
```

**Comment by tbenthompson** [comment]
Okay. So, it seems that pybind11 package installed the headers in `./include/site/python3.5` but pybind11.get_include(), which is supposed to return that directory, instead returns `/home/chadgh/.pyenv/versions/3.5.1/include/python3.5m/`. This is a problem with the [pybind11](https://github.com/pybind/pybind11) package. 

Wenzel Jakob, who is the maintainer of that project, is usually pretty responsive. Would you be up for opening an issue there? 

In the meantime, you can hack things to work properly by opening ./lib/python3.5/site-packages/pybind11/__init__.py and changing 
```python
return os.path.dirname(
            locations.distutils_scheme('pybind11', *args, **kwargs)['headers'])
```
to just have the hardcoded path where the `pybind11/pybind11.h` file is: In your case `YOURVIRTUALENVPATHNAME/include/site`.

**Comment by chadgh** [comment]
Hmm, @tbenthompson your suggestion didn't seem to work I replace the line you specified with:

`return '/home/chadgh/.virtualenvs/tmp-2ea8e0bcd287cca/include/site/python3.5/pybind11'`

And am getting the same error. I've confirmed that that is the location of the directory with all of the `.h` files.

Also, according to @wjakob this looks like it might be a pip issue. pypa/pip#3696

**Comment by chadgh** [comment]
I did just confirm that if I avoid the virtualenv, the example works.

**Comment by tbenthompson** [comment]
Glad we got to the root of the problem. Thanks for reporting this.

With you hack fix, the `pybind11` at the end of the line is the problem. It should be:
```
return '/home/chadgh/.virtualenvs/tmp-2ea8e0bcd287cca/include/site/python3.5'
```

**Comment by timbicker** [comment]
I have the same problem with python 3.7.

**Comment by tbenthompson** [comment]
Did you read through the posts above? This would be a problem with the installation of pybind11, its interaction with pip and the function `pybind11.get_include()`. There's nothing cppimport can do to fix it, but if you read through the posts above, there's a hack of that function that would probably work for you. Also, you can go look here for what seems like the latest update on the odyssey of fixing this problem: https://github.com/pybind/pybind11/pull/1190

**Comment by jvines** [comment]
Hi @timbicker ,

I mange to resolve this issue inside a virtualenv of python2.7 by installing pybind11 using conda install pybind11

Hope this helps

**Comment by timbicker** [comment]
Thanks for your help, I could solve the problem by doing the apt installs from the installation instruction.

**Comment by simonhughes22** [comment]
Installing pybind11 with conda first fixed it for me, as per @jvines' suggestion

**Comment by TeamATR** [comment]
I got the same error when I tried to install `scipy`. Is this [topic](https://github.com/scipy/scipy/issues/11241) related? It has been raised in Dec 2019. I am wondering how it is going? Any clue now?

**Comment by tbenthompson** [comment]
That `scipy` issue does seem similar. You might find some useful information scrolling back through this issue and some of the other linked issues.

**Comment by Adblu** [comment]
Same issue here:


    1.  pip to install
    2. ubuntu 18.04
    3. Python 3.6
    4. Virtualenv

How to fix it ?

**Comment by Adblu** [comment]
> Hi @timbicker ,
> 
> I mange to resolve this issue inside a virtualenv of python2.7 by installing pybind11 using conda install pybind11
> 
> Hope this helps

Thanks, it helped !

**Comment by Abduhu** [comment]
I had same problem. It seems that pip does not include pyind11 properly. Hence, I reintalled pybind11 manullay after cloning the package from github repository.
Resume: install pybind11 by pybind11/setup.py instead of pip of Pypi

**Comment by tbenthompson** [comment]
> I had same problem. It seems that pip does not include pybind11 properly. Hence, I reinstalled pybind11 manully after cloning the package from github repository.
> Resume: install pybind11 by pybind11/setup.py instead of pip of Pypi

It seems like the PyPI (pip) pybind11 package works for some people and not others. Have you tried the conda pybind11 package? That seems to consistently work, but obviously is useless if you're not using conda.

**Comment by rongduo** [comment]
I met the same error when I tried to compile a simple c++ extension module. I found that this can be solved in by adding
`from setuptools import find_packages, setup'

**Comment by tanzhenyu** [comment]
> Hi @timbicker ,
> 
> I mange to resolve this issue inside a virtualenv of python2.7 by installing pybind11 using conda install pybind11
> 
> Hope this helps

I can confirm this works with python3.8 as well.

**Comment by dman82499** [comment]
just confirmed the pip installation of pybind does not install the .h files for me as well, weird. Using windows with python 3.7.4

**Comment by tbenthompson** [comment]
> just confirmed the pip installation of pybind does not install the .h files for me as well, weird. Using windows with python 3.7.4. However, using pip install pybind11[global] fixed the issue for me.

Glad you got the issue resolved! You might leave post an issue to the pybind11 github issue tracker.

**Comment by borgarpa** [comment]
> Hi @timbicker ,
> 
> I mange to resolve this issue inside a virtualenv of python2.7 by installing pybind11 using conda install pybind11
> 
> Hope this helps

It didn't work for me tho... I don't know why, but in my conda env it is just impossible for me to get pybind11 to work...
```
/home/borgarpa/miniconda3/envs/torch-points_rocm/lib/python3.8/site-packages/torch/include/torch/csrc/utils/pybind.h:6:10: fatal error: pybind11/pybind11.h: No such file or directory
      6 | #include <pybind11/pybind11.h>
        |          ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
```

**Comment by tbenthompson** [comment]
Hi @borgarpa 

I don't have a solution for you, but I just wanted to mention something that looks a bit funny to me. In the `gcc` command from your output, I don't see the pybind11 include directories being included with a `-I`. You might check the output of
```
import pybind11
pybind11.get_include()
```
That folder should show up in the `gcc` command.

For me, I get:
```
(cppimport) ➜  ~ python
Python 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:55:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybind11
>>> pybind11.get_include()
'/home/tbent/.miniconda3/envs/cppimport/lib/python3.9/site-packages/pybind11/include'
```

**Comment by DSRajesh** [comment]
> Hi @borgarpa
> 
> I don't have a solution for you, but I just wanted to mention something that looks a bit funny to me. In the `gcc` command from your output, I don't see the pybind11 include directories being included with a `-I`. You might check the output of
> 
> ```
> import pybind11
> pybind11.get_include()
> ```
> 
> That folder should show up in the `gcc` command.
> 
> For me, I get:
> 
> ```
> (cppimport) ➜  ~ python
> Python 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:55:42)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pybind11
> >>> pybind11.get_include()
> '/home/tbent/.miniconda3/envs/cppimport/lib/python3.9/site-packages/pybind11/include'
> ```

this worked for me. Thanks  Mr. benthompson
